apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: big-corp-app
  name: big-corp-app
spec:
  containers:
  - image: nginx
    name: big-corp-app
    resources: {}
  - name: sidecar
    image: busybox
    args: ["tail", "-n+1", "-f", "/var/log/dpkg.log"]
  volumes:
  - name: log-volume
    hostPath:
      path: /var/log
  volumeMounts:
  - name: log-volume
    mountPath: /var/log