apiVersion: v1
kind: Pod
metadata:
  name: big-corp-app
spec:
  initContainers:
  - name: create-log-dir
    image: busybox
    command: ['mkdir', '-p', '/var/log/nginx']
    volumeMounts:
    - name: log-volume
      mountPath: /var/log
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: log-volume
      mountPath: /var/log
  - name: sidecar
    image: busybox
    args: ["tail", "-n+1", "-f", "/var/log/dpkg.log"]
    volumeMounts:
    - name: log-volume
      mountPath: /var/log
  volumes:
  - name: log-volume
    hostPath:
      path: /var/log
